### ISSUE TITLE
hefesto issue

### ISSUE THREAD

**Issue by demahom27** [rafael-santiago/mr-hyde#1]
i have this issue when running hefesto 
hefesto WARNING: unable to resolve file name "~/toolsets/null/null.hsl" 
hefesto WARNING: unable to resolve file name "~/toolsets/null/null.hsl" 
hefesto: script compilation success.
hefesto WARNING: unable to resolve file name "~/toolsets/null/null.hsl" 
hefesto: toolset load failure.

Seems like some files are missing.

**Comment by rafael-santiago** [comment]
If you have just finished Hefesto's installing process try to logout and then login again. It seems that your ``HEFESTO_INCLUDE_HOME`` environment variable was not really loaded or set accordingly at the failure moment.
